export const AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE';

export const EMPLOYEE_SERVICE = 'EMPLOYEE_SERVICE';

export const COMPANY_SERVICE = 'COMPANY_SERVICE';
export const NATS_SERVICE = 'NATS_SERVICE';
